/**:
  ros__parameters:
    cmd_freq: 30.0  # Command send frequency to the platform (default: 30.0 Hz)
    info_freq: 10.0  # Info send frequency to ROS 2 (default: 10.0 Hz)
    enable_camera: false  # Enable camera image publishing (default: false)
    enable_gimbal: false  # Enable gimbal control (default: false)
    tf_timeout_threshold: 0.05 # tf timeout (default: 0.05 s)