/**:
  ros__parameters:
    num_of_initialization_retries: 3

    imu_frame: "imu_link"
    body_frame: "base_link"
    map_frame: "psdk_map_enu"
    gimbal_base_frame: "gimbal_base"
    gimbal_frame: "gimbal"
    camera_frame: "camera_link"
    publish_transforms: true

    file_path: "/tmp/"

    # Mandatory modules to be initialized. Mark with a true those which you 
    # consider mandatory for your application, false otherwise. Be aware that 
    # some modules might have inter-dependencies. Non mandatory modules will
    # still be initialized but if case of failure, the node will continue to run.
    mandatory_modules:
      telemetry: true
      flight_control: true
      camera: false
      gimbal: false
      liveview: false
      hms: false
      perception: false

    data_frequency: # Options are: 1, 5, 10, 50, 100, 200, 400 Hz 
      imu: 1
      attitude: 10
      acceleration: 10
      velocity: 50
      angular_velocity: 10
      position: 50
      altitude: 50
      gps_fused_position: 50
      gps_data: 1
      rtk_data: 50
      magnetometer: 1
      rc_channels_data: 1
      gimbal_data: 10
      flight_status: 1
      battery_level: 1
      control_information: 1
      esc_data_frequency: 1

